//! mermaid-ascii — Mermaid flowchart syntax to ASCII/Unicode text renderer.
//!
//! .hom source files are compiled to .rs by build.rs → homunc into OUT_DIR.
//! Hand-written Rust helpers live in graph/.

#![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros, unused_assignments)]
#![allow(non_snake_case)]

// ── Homun runtime (builtin + std + re + heap) ──────────────────────────────
// Generated by build.rs from a stub .hom. Provides macros (range!, len!, filter!,
// map!, dict!, set!, slice!, homun_in!), traits (HomunIndex, HomunLen, HomunContains),
// and all std library functions (split, join, trim, sorted, etc.).
#[macro_use]
pub mod runtime { include!(concat!(env!("OUT_DIR"), "/runtime.rs")); }

// graph/ — hand-written Rust helper modules (petgraph wrapper + mutable state types)
#[path = "graph/mod.rs"]
pub mod graph;

// Generated .hom modules live in OUT_DIR.
// Each module gets `use crate::runtime::*` for access to std functions/macros.
mod types {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/types.rs"));
}
mod config {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}
mod layout_types {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/layout_types.rs"));
}
mod charset {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/charset.rs"));
}
mod canvas {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/canvas.rs"));
}
mod parser {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/parser.rs"));
}
mod pathfinder {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/pathfinder.rs"));
}
mod layout {
    use crate::runtime::*;
    include!(concat!(env!("OUT_DIR"), "/layout.rs"));
}

/// Parse a Mermaid flowchart string and render it to ASCII/Unicode art.
///
/// Full implementation wires: parse → GraphIR → layout → renderer.
pub fn render_dsl(
    _src: &str,
    _unicode: bool,
    _padding: usize,
    _direction: Option<&str>,
) -> Result<String, String> {
    Err("not yet implemented — modules are being ported to .hom".to_string())
}
